from __future__ import annotations

from enum import Enum


class MainRequestCategoryEnum(str, Enum):
    TEMPORARY_RESIDENCE = "TEMPORARY_RESIDENCE"
    PERMANENT_RESIDENCE = "PERMANENT_RESIDENCE"
    MODIFICATION = "MODIFICATION"
    DEREGISTRATION = "DEREGISTRATION"


class PermanentResidenceGroundEnum(str, Enum):
    CONTINUOUS_5_YEARS = "CONTINUOUS_5_YEARS"
    RETIREMENT_WITH_12_MONTHS_AND_3_YEARS = "RETIREMENT_WITH_12_MONTHS_AND_3_YEARS"
    RETIREMENT_WITH_SPANISH_SPOUSE = "RETIREMENT_WITH_SPANISH_SPOUSE"
    RETIREMENT_WITH_SPOUSE_LOST_SPANISH_NATIONALITY = "RETIREMENT_WITH_SPOUSE_LOST_SPANISH_NATIONALITY"
    EARLY_RETIREMENT_WITH_12_MONTHS_AND_3_YEARS = "EARLY_RETIREMENT_WITH_12_MONTHS_AND_3_YEARS"
    EARLY_RETIREMENT_WITH_SPANISH_SPOUSE = "EARLY_RETIREMENT_WITH_SPANISH_SPOUSE"
    EARLY_RETIREMENT_WITH_SPOUSE_LOST_SPANISH_NATIONALITY = "EARLY_RETIREMENT_WITH_SPOUSE_LOST_SPANISH_NATIONALITY"
    PERMANENT_DISABILITY_AFTER_2_YEARS = "PERMANENT_DISABILITY_AFTER_2_YEARS"
    PERMANENT_DISABILITY_WORK_ACCIDENT = "PERMANENT_DISABILITY_WORK_ACCIDENT"
    PERMANENT_DISABILITY_WITH_SPANISH_SPOUSE = "PERMANENT_DISABILITY_WITH_SPANISH_SPOUSE"
    PERMANENT_DISABILITY_WITH_SPOUSE_LOST_SPANISH_NATIONALITY = "PERMANENT_DISABILITY_WITH_SPOUSE_LOST_SPANISH_NATIONALITY"
    WORK_IN_OTHER_MEMBER_STATE_KEEPING_RESIDENCE = "WORK_IN_OTHER_MEMBER_STATE_KEEPING_RESIDENCE"
    OTHER = "OTHER"


class ModificationGroundEnum(str, Enum):
    PERSONAL_DATA = "PERSONAL_DATA"
    ADDRESS_CHANGE = "ADDRESS_CHANGE"
    IDENTITY_DOCUMENT_CHANGE = "IDENTITY_DOCUMENT_CHANGE"
    OTHER = "OTHER"
